### ISSUE TITLE
Contact address for bug reports points to the defunct SourceForge repository 

### ISSUE THREAD

**Issue by hlapp** [TreeBASE/treebase#1]
See here: http://treebase.org/treebase-web/contact.html

> Alternatively, you can enter a bug report directly into our SourceForge online bug tracker. For that, please follow these steps:

> 1. If you have a SourceForge account, log in to it and proceed to (II) below. Otherwise visit http://sourceforge.net/account/registration/ and fill in the form. After you confirm the account creation by email, log in at http://sourceforge.net/account/login.php
> 2. Visit https://sourceforge.net/tracker2/?group_id=248804&atid=1126676. On this page you can browse the bug database.
> 3. Click the "add new" button.  Add the description of the bug.  Long outputs or error messages can be attached as separate files if you prefer. Click "add artifact" to submit the report.

**Comment by fpieters** [comment]
I changed the page in production

**Comment by hlapp** [comment]
The pull request (#2) remains unmarked though? Did you modify the code locally?
