### ISSUE TITLE
Better document on the UI which NEXUS flavors are supported

### ISSUE THREAD

**Issue by ghost** [TreeBASE/treebase#188]
Some people have submitted NEXUS files that we know we do not support, such as certain ones created by MrBayes. We need to document more clearly on the submission UI which NEXUS creators and flavors we support and what to do if a submitter's file was created by a different program. 

Reported by: hlapp

**Comment by rvosa** [comment]
The submission tutorial states clearly enough that Mesquite needs to be able to parse a Nexus file and otherwise it's not valid.
