### ISSUE TITLE
Unable to delete Study

### ISSUE THREAD

**Issue by ghost** [TreeBASE/treebase#238]
I am unable to delete an in progress submission 12711. When I attempt to delete it, TreeBASE gives me this error message:
Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1

I'm guessing this has something to do with the recent server migration?

Reported by: jonesmcc

**Comment by rvosa** [comment]
This is not really a bug, but just how the data model works. It's a bit cumbersome but not a showstopper. Closing this, but feel free to bring it back up.
