### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ghost** [TreeBASE/treebase#239]
On the the page http://www.treebase.org/treebase-web/home.html, which describes the features of treebase, there is a string which reads:
"Data are delivered in several serializations, including NEXUS and NeXML"

It appears that the link for "NEXUS" is broken. When clicked, the link takes you to this page: http://www.treebase.org/hackathon.nescent.org/Supporting\_NEXUS\_Documentation, which says: "Sorry, page not found. You may continue your search here". 

Perhaps the link should direct here (http://informatics.nescent.org/wiki/Supporting\_NEXUS\), instead?

Reported by: jonesmcc

**Comment by rvosa** [comment]
Fixed as of a48f08caa83aa13a106660200b275585336b3502
