### ISSUE TITLE
stability of edge IDs in repeated requests for the same study

### ISSUE THREAD

**Issue by mtholder** [TreeBASE/treebase#262]
This is a question rather than a bug report - or rather it might be just a question

If you request a study in nexml form twice (e.g. load https://treebase.org/treebase-web/search/downloadAStudy.html?id=15515&format=nexml in one window and then load it again) then you'll see that the edge IDs differ in the 2 instance docs.

Is this a bug or a feature?

I think both versions are valid NeXML. So it is not obviously a bug, but it would be nice if the canonical NeXML representation of a study had persistent IDs so that other tools could rely on the IDs.

**Comment by piel** [comment]
Hi Mark,

I’m guessing that these edge IDs are viewed as “anonymous” or arbitrary — kind of like the index symbols of a translation table in a tree block. Only things with fully qualified URIs should be considered as usable IDs.  I’m not sure I would want to give meaning to IDs for the parts of trees that are unordered (e.g. two topologically perfectly congruent trees might have very different IDs if internal nodes are flipped -- despite using the same method of traversal). But maybe our usage runs contrary to the spirit of XML. Still, I’m amazed that the XML writer generates different results from two identical requests, unless some kind of random seed is changing things. Rutger undoubtedly knows the answer to this.

bp

**Comment by mtholder** [comment]
FWIW it looks like the edge IDs are generated by concatenating "edge" with a the string representation of some counter that keeps getting bigger.

**Comment by hlapp** [comment]
It should be noted that all IDs in a NeXML document are local and not required to be round tripped or persisted in any other way. They _may_ be taken from a persistent database IDs, but client code should never rely on that.

**Comment by mtholder** [comment]
yup that why I said that I thought they were both valid NeXML.

The question is whether TreeBASE would like offer stable IDs as a benefit to its users. 

Edges on trees are a core part of phylogenetic hypotheses, so it seems like it would be nice for an auxiliary db to refer to edgeXYZ in studyABC.

That being said, I can certainly accept if the developers don't want to support this feature. I'm afraid that I don't have time to delve into the code and suggest an edit.

**Comment by rvosa** [comment]
TreeBASE NeXML IDs could be stable for a while if NeXML output is cached on
the server side but you can't rely on it and this is not likely to change.
