### ISSUE TITLE
Trouble uploading NEXUS format multiple sequence alignment file

### ISSUE THREAD

**Issue by BrianFoley** [TreeBASE/treebase#263]
I have a multiple sequence alignment, in FASTA format.  I have used two different tools to convert the FASTA format file to NEXUS format, with similar but not identical results.  The NEXUS files are both valid NEXUS format files, and they can be opened and used with alignment editors and phylogenetic analysis programs such as PAUP, AliView, BioEdit, PhyML, MEGA. But only one of the NEXUS format files can be read with MESQUITE, and neither of them works well with TreeBASE.  

I am attaching the FASTA format and NEXUS format files here, in case anyone wants to play with them.  I renamed the file extenstions from .FASTA and .nex to .txt because GitHub will not accept files named with .FASTA or .nex extensions.  But all of these file formats are just plain ASCII text anyway.

[Lepto_16S_FewerTrimmedFASTA.txt](https://github.com/TreeBASE/treebase/files/240849/Lepto_16S_FewerTrimmedFASTA.txt)
[Lepto_16S_FewerTrimmed_IQtreNEXUS.txt](https://github.com/TreeBASE/treebase/files/240845/Lepto_16S_FewerTrimmed_IQtreNEXUS.txt)
[Lepto_16S_FewerTrimmedNEXUS.txt](https://github.com/TreeBASE/treebase/files/240846/Lepto_16S_FewerTrimmedNEXUS.txt)
[Lepto_16S_FewerTrimmedNEXUS3.txt](https://github.com/TreeBASE/treebase/files/240847/Lepto_16S_FewerTrimmedNEXUS3.txt)

**Comment by piel** [comment]
> On Apr 28, 2016, at 11:30 PM, Brian Foley <notifications@github.com> wrote:
> 
> I have a multiple sequence alignment, in FASTA format. I have used two different tools to convert the FASTA format file to NEXUS format, with similar but not identical results. The NEXUS files are both valid NEXUS format files, and they can be opened and used with alignment editors and phylogenetic analysis programs such as PAUP, AliView, BioEdit, PhyML, MEGA. But only one of the NEXUS format files can be read with MESQUITE, and neither of them works well with TreeBASE.
> 
> I am attaching the FASTA format and NEXUS format files here, in case anyone wants to play with them. I renamed the file extenstions from .FASTA and .nex to .txt because GitHub will not accept files named with .FASTA or .nex extensions. But all of these file formats are just plain ASCII text anyway.
> 
> Lepto_16S_FewerTrimmedFASTA.txt <https://github.com/TreeBASE/treebase/files/240849/Lepto_16S_FewerTrimmedFASTA.txt>
> Lepto_16S_FewerTrimmed_IQtreNEXUS.txt <https://github.com/TreeBASE/treebase/files/240845/Lepto_16S_FewerTrimmed_IQtreNEXUS.txt>
> Lepto_16S_FewerTrimmedNEXUS.txt <https://github.com/TreeBASE/treebase/files/240846/Lepto_16S_FewerTrimmedNEXUS.txt>
> Lepto_16S_FewerTrimmedNEXUS3.txt <https://github.com/TreeBASE/treebase/files/240847/Lepto_16S_FewerTrimmedNEXUS3.txt>
The main problem seems to be with the hard-coding of underscores, and inconsistencies therein can cause the tree to fail to mate with the alignment in Mesquite. 

I have fixed these problems in the attached nexus, which you can open in Mesquite. Note that we require taxon labels to be prefixed with the taxon name and (optionally) suffixed by any special codes. I edited Katavi1 to “Leptospira interrogans Katavi1” — please fix if this is incorrect. 

regards,

Bill

**Comment by BrianFoley** [comment]
I was not able to see the file that Bill Piel very kindly created for me above, but I was able to solve the problem myself while waiting for replies here.  I am attaching the Mesquite file here (alignment and tree all wrapped up in one file) and a PDF of the tree similar to what the user plans to publish.


[_LeptoNEXUS.txt](https://github.com/TreeBASE/treebase/files/242822/_LeptoNEXUS.txt)
[_LeptoNEXUS_IQtreePDF.pdf](https://github.com/TreeBASE/treebase/files/242824/_LeptoNEXUS_IQtreePDF.pdf)

Anyway, I very much appreciate you speedy reply and help with this.  But I would also like to help in any way I can to make the data submission process easier.  I think TreeBASE is a great resource, and I can think of a few tools and tutorial help messages that might smooth the process.  For one example, this user came to me with data that was named  with a mix of Accession_Genus_species and Genus_species_Accession so the first step was to fix that.  But more importantly was to figure out why he had two name orders and help him not do that in the future.

Once I had consistent names, I could then use some tools to re-order the names and make them consistent. At first I used Genus_species-accession but then I found that Mesquite replaced the "-" with "_" which would  make parsing the names difficult in the future.  I wanted a unique character between name and accession  to facilitate future parsing of the files.  Using a tilde seems to work.  (some other characters like @ and $ and * may be legal here, but risky for PERL and other scripting languages).  The underscore was problematic in part because of the accession numbers sometimes having an underscore (NR_043048 for example) so we can't just take everything right of the last underscore as accession number.

**Comment by piel** [comment]
> On Apr 30, 2016, at 12:41 AM, Brian Foley <notifications@github.com> wrote:
> 
> I was not able to see the file that Bill Piel very kindly created for me above, but I was able to solve the problem myself while waiting for replies here. I am attaching the Mesquite file here (alignment and tree all wrapped up in one file) and a PDF of the tree similar to what the user plans to publish.
> 
> _LeptoNEXUS.txt <https://github.com/TreeBASE/treebase/files/242822/_LeptoNEXUS.txt>
> _LeptoNEXUS_IQtreePDF.pdf <https://github.com/TreeBASE/treebase/files/242824/_LeptoNEXUS_IQtreePDF.pdf>
> Anyway, I very much appreciate you speedy reply and help with this. But I would also like to help in any way I can to make the data submission process easier. I think TreeBASE is a great resource, and I can think of a few tools and tutorial help messages that might smooth the process. For one example, this user came to me with data that was named with a mix of Accession_Genus_species and Genus_species_Accession so the first step was to fix that. But more importantly was to figure out why he had two name orders and help him not do that in the future.
> 
> Once I had consistent names, I could then use some tools to re-order the names and make them consistent. At first I used Genus_species-accession but then I found that Mesquite replaced the "-" with "_" which would make parsing the names difficult in the future. I wanted a unique character between name and accession to facilitate future parsing of the files. Using a tilde seems to work. (some other characters like @ and $ and * may be legal here, but risky for PERL and other scripting languages). The underscore was problematic in part because of the accession numbers sometimes having an underscore (NR_043048 for example) so we can't just take everything right of the last underscore as accession number.
> 
Hi Brian,

Attached is your NEXUS file that I’ve further edited. I’ll also attach a zipped version in case text attachments are getting removed somehow. 

One problem is a little complicated to explain. Basically, Mesquite saves all the “actions” you do (mouse clicks on menus, etc), and if you save the project and then reopen it, Mesquite will recreate all those actions to restore you to the state where you last left off. The problem is that other NEXUS parsers can’t understand the Mesquite block, so they can’t recreate the state. They can only read trees that are stored in a trees block in the NEXUS, not in the Mesquite block.  At any rate, I’ve fixed this by opening the file in Mesquite and doing “Store tree” from the Trees menu — that obliges Mesquite to generate a tree block and store the tree in there. 

I made two other changes: 
- I replaced the tilde with a space. This is because I’m not sure how uBio will handle a tilde when doing taxon name mapping
- I reintroduced the underscore in the “NR_” codes. This is because they are part of the ID.

I uploaded this to S19234 — assuming that this is where it belonged. But I just noticed that there is no “B Foley” in the author list, so perhaps I put it in the wrong submission. Shaman Muller can delete this if it’s in the wrong place. Else that submission looks ready to go.

regards,

Bill

**Comment by rvosa** [comment]
@BrianFoley is this still an issue or can this be closed?

**Comment by BrianFoley** [comment]
I think you should close it.

Brian Foley, PhD
HIV Databases
http://hiv.lanl.gov
btf@lanl.gov<mailto:btf@lanl.gov>
(505) 665-1970



On Jul 19, 2017, at 6:37 PM, Rutger Vos <notifications@github.com<mailto:notifications@github.com>> wrote:


@BrianFoley<https://github.com/brianfoley> is this still an issue or can this be closed?
