### ISSUE TITLE
Use OpenTree of Life TNRS

### ISSUE THREAD

**Issue by fmichonneau** [TreeBASE/treebase#265]
NCBI taxonomy is incomplete, and the other option provided by TreeBASE (ubio.org) seems gone (or at least has been done for 1+ week now). OpenTree of Life provides the most comprehensive TNRS currently by aggregating multiple databases (incl. NCBI), and should probably be used to match taxon names.

**Comment by rvosa** [comment]
uBio is back, and it's going to be too much work to switch to OpenTOL TNRS.
