### ISSUE TITLE
Shen et al salamander study has wrong ID number?

### ISSUE THREAD

**Issue by BrianFoley** [TreeBASE/treebase#266]
Shen et al 
Enlarged Multilocus Data set Provides Surprisingly Younger Time of Origin for the Plethodontidae, the Largest Family of Salamanders.
https://www.ncbi.nlm.nih.gov/pubmed/26385618

has this link in paper:
The data matrices and resulting trees were deposited in TreeBase
(http://purl.org/phylo/treebase/phylows/study/TB2:S17263 ).

but that link goes to a hornworts data set.

**Comment by rvosa** [comment]
They put it wrong in their paper, it should be S17236
