### ISSUE TITLE
No response from help@treebase.org

### ISSUE THREAD

**Issue by jaylward2** [TreeBASE/treebase#281]
I submitted an alignment and phylogeny to TreeBase almost a month ago (3 Sep), but nothing seems to be happening in terms of processing the submission. Also no response from the mailing address.

Does anyone have an idea what is going on?

**Comment by stefanekman** [comment]
If you ask me, TreeBase is dead. I have had no response from help@treebase.org to emails sent from January 2019 onwards. The last time an issue was closed on GitHub was 4 Jan 2018. I have stopped using TreeBase as a repository.

**Comment by rvosa** [comment]
This is not entirely true. The issue with the email address was a temporary
problem with the sendmail configuration that now has been fixed. Meanwhile,
Bill Piel is working through a backlog of problematic submissions, but it's
slow going. If you have a specific submission that is being unduly held up
you might want to get in touch with him directly.

**Comment by rvosa** [comment]
We aware of the problems. Whether they can be addressed is being investigated. Right now the project lacks resources for full time programmer support, which is needed.
