### ISSUE TITLE
Treebase intermittently unresponsive

### ISSUE THREAD

**Issue by w0elfin** [TreeBASE/treebase#283]
In trying to upload my files, I keep encounting various problems (e.g. unable to log on, unable to upload files). In a previous response it was mentioned that a build up of temporary files can make Treebase become unresponsive. Is it time for another reboot to clear those temporary files?

Thanks,
Andrea

**Comment by rvosa** [comment]
We aware of the problems. Whether they can be addressed is being investigated. Right now the project lacks resources for full time programmer support, which is needed.
