### ISSUE TITLE
Treebase not working

### ISSUE THREAD

**Issue by NiloofarVaghefi** [TreeBASE/treebase#284]
Hi there
I have been trying to access Treebase but cannot log in. It does not accept my username/pass but does not tell me what is wrong either. Is the website currently functional or the problem is on my side?
Thanks
Niloofar

**Comment by dsenalik** [comment]
Treebase has seemed to be abandoned for several years now, you'll find a number of other open issues here with no resolution. Sometimes it is up and running but often not. Does anyone know any more?

**Comment by rvosa** [comment]
We aware of the problems. Whether they can be addressed is being investigated. Right now the project lacks resources for full time programmer support, which is needed.

**Comment by dsenalik** [comment]
Closing an issue without addressing the problem does not make the problem go away, these issues should remain open until resolved.

**Comment by hlapp** [comment]
Perhaps the better status than _Close as completed_ would be _Close as not planned_? I.e., there is no plan currently to secure funding and resources, if I understand this right?
