### ISSUE TITLE
Technology page

### ISSUE THREAD

**Issue by tjv** [TreeBASE/treebase#4]
points to sourceforge repo and wiki rather than github https://treebase.org/treebase-web/technology.html

**Comment by fpieters** [comment]
I changed the page in production. Still missing is the wiki page: https://github.com/TreeBASE/treebase/wiki/Documentation

**Comment by hlapp** [comment]
I don't see a pull request or commit that does this?

**Comment by rvosa** [comment]
Foppe is referring to a hardcoded fix in the JSP files on the server.
Unfortunately there is currently no commit/compile/deploy automation.

**Comment by hlapp** [comment]
I didn't say it needs to be automated. But I think we all agree that having changes in deployed code that are nowhere to be found in the repo is rather dangerous?

**Comment by rvosa** [comment]
This has been fixed in the source repo.
