### ISSUE TITLE
Commit / compile / deploy automation

### ISSUE THREAD

**Issue by rvosa** [TreeBASE/treebase#8]
@hlapp asks in several issue threads (#1, #7, #4, #5) how it can be that @fpieters is making changes in production that aren't reflected in the code base, and he makes the argument that this is dangerous. Indeed it is, and it has to stop, but here's why this is happening:

The current deployment of TreeBASE on Naturalis's servers is a direct copy of the artifacts that were on the server at NESCent that was hosting TreeBASE. This includes the JSP pages that @fpieters has been editing.

We obviously don't want a situation where pages are being edited "live" on the server, and much less so if these changes don't make it back into the source tree. This issue is meant as the place to sketch out a strategy for making this stop. Broadly speaking, I think this would be the most elegant way to do this:
1. We write a puppet manifest that automates the build. This is going to wrap around the dependency management (maven, headless mesquite, phylowidget) and the compilation and deployment steps.
2. Commits to the TreeBASE repo trigger the build process on some test / continuous integration server. I wonder if it might be possible to do this on travis (you can set rather long timeouts) in such a way that we get meaningful feedback e.g. when optionally running the unit tests.
3. If all appears to be well and there are substantial changes that need to go live we deploy the produced artifacts on the production server.

Makes sense?

**Comment by rvosa** [comment]
Ok, thinking this through a little bit more, what I've done so far as check whether the `pom.xml` files for maven can be resurrected.  It turns out that, as of commit ced0beecd54a221e29ae3d181f19eda84ce112d2, it is possible to run `mvn compile` to completion in the root folder. This doesn't yet result in a `war` artifact (not sure why) but presumably it is possible to get this to work so that building and deployment can be automated to a reasonable extent.

I also created a `.travis.yml`, the thinking being that commits might trigger an `mvn test` on a travis server so that we know that any changes don't screw things up. Unfortunately, the test suite is not designed in such a way that at least part of it can be run without database access. Perhaps it is possible to run the unit tests against a remote database instance? I.e. travis connects to the TreeBASE prod service (or clone thereof) to run the DAO tests.

**Comment by piel** [comment]
> On Jan 25, 2016, at 11:29 PM, Rutger Vos <notifications@github.com> wrote:
> 
> Unfortunately, the test suite is not designed in such a way that at least part of it can be run without database access. Perhaps it is possible to run the unit tests against a remote database instance? I.e. travis connects to the TreeBASE prod service (or clone thereof) to run the DAO tests.

That would suite me well — in that I’d love to be able to have direct SQL access to a nightly-updated postgresql mirror. 

bp

**Comment by rvosa** [comment]
Here's what now needs to happen, and I will need some input on a number of these issues:
1. we can't run the unit tests on a continuous integration server as long as we don't have a database server we can safely connect to (i.e. not the production server). Hence, we need a postgresql mirror.
2. we can't create a war file for deployment on a server from the top level of the source tree. I don't know how to fix this. It seems to have something to do with dependencies of treebase-web on treebase-core.
3. even if we can create a war file we need to test if it is compatible with newer versions of tomcat, as the one we're using is reaching end of life.
I can't do anything about 1); and 2) and 3) are more work than I am likely to be able to fit into my copious amounts of spare time. Let's all be aware of this.

**Comment by rvosa** [comment]
Hi Foppe,

kunnen we jou vragen om een mirror van de postgres server aan te leggen?

Thanks,

Rutger

**Comment by fpieters** [comment]
Natuurlijk...
Im working on the database replication

**Comment by rvosa** [comment]
Building a WAR file is now basically fully automated from the top level of the source tree, as described here: https://github.com/TreeBASE/treebase/blob/master/BUILDING.md

It also appears that the new WAR file is compatible with Tomcat7.

**Comment by piel** [comment]
Holy cow!  Are you saying TreeBASE can be brought up to date?  Wow!  A number of journals that have committed to TreeBASE have asked me to add them to our website, which thus far I’ve had to decline. This is cool. 

bp
